mode = "light"

accent = "#F9C3D9"
selection = "#cca0b2"
muted = "#bfa1ad"

background = "#F9C3D9"
dark_background = "#e3b1c5"
darker_background = "#d1a4b6"
lighter_background = "#facee0"

foreground = "#1F1B24"
dark_foreground = "#886c7b"
light_foreground = "#463945"
bright_foreground = "#1F1B24"

red = "#D83A56"
yellow = "#D69E20"
orange = "#DE7138"
green = "#32945A"
cyan = "#249AA8"
blue = "#2774D8"
magenta = "#C43D9B"
brown = "#8A5A3A"

bright_red = "#F05269"
bright_yellow = "#F2BE3D"
bright_green = "#4CBF76"
bright_cyan = "#43C1CF"
bright_blue = "#4A91F0"
bright_magenta = "#E25BBB"
