mode = "dark"

accent = "#1668E0"
selection = "#4083e6"
muted = "#426fb1"

background = "#1668E0"
dark_background = "#1151af"
darker_background = "#0f4594"
lighter_background = "#4083e6"

foreground = "#FFFFFF"
dark_foreground = "#8fb7f0"
light_foreground = "#d5e4f9"
bright_foreground = "#FFFFFF"

red = "#D83A56"
yellow = "#D69E20"
orange = "#DE7138"
green = "#32945A"
cyan = "#249AA8"
blue = "#2774D8"
magenta = "#C43D9B"
brown = "#8A5A3A"

bright_red = "#F05269"
bright_yellow = "#F2BE3D"
bright_green = "#4CBF76"
bright_cyan = "#43C1CF"
bright_blue = "#4A91F0"
bright_magenta = "#E25BBB"
