mode = "light"

accent = "#E0A32A"
selection = "#b88622"
muted = "#b18f4d"

background = "#E0A32A"
dark_background = "#cc9426"
darker_background = "#bc8923"
lighter_background = "#e6b450"

foreground = "#1F1B24"
dark_foreground = "#7c5c27"
light_foreground = "#423325"
bright_foreground = "#1F1B24"

red = "#D83A56"
yellow = "#D69E20"
orange = "#DE7138"
green = "#32945A"
cyan = "#249AA8"
blue = "#2774D8"
magenta = "#C43D9B"
brown = "#8A5A3A"

bright_red = "#F05269"
bright_yellow = "#F2BE3D"
bright_green = "#4CBF76"
bright_cyan = "#43C1CF"
bright_blue = "#4A91F0"
bright_magenta = "#E25BBB"
